namespace Agentic_Browser
{
    [default_interface]
    runtimeclass BrowserView : Microsoft.UI.Xaml.Controls.Page
    {
        BrowserView();
        
        void NavigateTo(String url);
        void Cleanup();

        event Windows.Foundation.TypedEventHandler<BrowserView, String> TitleChanged;
        event Windows.Foundation.TypedEventHandler<BrowserView, String> FaviconChanged;
        event Windows.Foundation.TypedEventHandler<BrowserView, String> NewTabRequested;
        
    }
}
